### ISSUE TITLE
Error starting container, missing envkey DJANGO_SECRET_KEY

### ISSUE THREAD

**Issue by mp-se** [mp-se/fermentrack-docker#35]
Creating fermentrack ... done
Attaching to fermentrack
fermentrack    | Checking if all required volumes are mounted correctly
fermentrack    | Volume for data and database are mounted.
fermentrack    | Copying secret settings from db folder to image
fermentrack    | Setting correct access rights on mounted volumes
fermentrack    | Version of main linux packages installed in image:
fermentrack    | ****************************************************************
fermentrack    | Debian GNU/Linux 10 \n \l
fermentrack    |
fermentrack    | nginx version: nginx/1.14.2
fermentrack    | Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=94145a25ce04923
fermentrack    | Python 3.7.3
fermentrack    | Image build date:
fermentrack    | Tue Apr 20 19:10:35 UTC 2021
fermentrack    | Starting NGINX
fermentrack    | Starting REDIS
fermentrack    | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
fermentrack    | Checking if the container is running in priviliged mode
fermentrack    | Failed to set capabilities on file `/usr/bin/python3.7' (Operation not supported)
fermentrack    | The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
fermentrack    | Failed to set capabilities on file `/usr/bin/python3.7' (Operation not supported)
fermentrack    | The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
fermentrack    | Container is NOT running in priviligied mode (2)
fermentrack    | Starting Fermentrack
fermentrack    | Collecting static files
fermentrack    | Traceback (most recent call last):
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 273, in get_value
fermentrack    |     value = self.ENVIRON[var]
fermentrack    |   File "/usr/lib/python3.7/os.py", line 678, in __getitem__
fermentrack    |     raise KeyError(key) from None
fermentrack    | KeyError: 'DJANGO_SECRET_KEY'
fermentrack    |
fermentrack    | During handling of the above exception, another exception occurred:
fermentrack    |
fermentrack    | Traceback (most recent call last):
fermentrack    |   File "manage.py", line 25, in <module>
fermentrack    |     execute_from_command_line(sys.argv)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
fermentrack    |     utility.execute()
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
fermentrack    |     self.fetch_command(subcommand).run_from_argv(self.argv)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 231, in fetch_command
fermentrack    |     settings.INSTALLED_APPS
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
fermentrack    |     self._setup(name)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
fermentrack    |     self._wrapped = Settings(settings_module)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
fermentrack    |     mod = importlib.import_module(self.SETTINGS_MODULE)
fermentrack    |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
fermentrack    |     return _bootstrap._gcd_import(name[level:], package, level)
fermentrack    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
fermentrack    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
fermentrack    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
fermentrack    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
fermentrack    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
fermentrack    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
fermentrack    |   File "/home/fermentrack/fermentrack/fermentrack_django/settings.py", line 26, in <module>
fermentrack    |     SECRET_KEY = env("DJANGO_SECRET_KEY")
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 123, in __call__
fermentrack    |     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 277, in get_value
fermentrack    |     raise ImproperlyConfigured(error_msg)
fermentrack    | django.core.exceptions.ImproperlyConfigured: Set the DJANGO_SECRET_KEY environment variable
fermentrack    | Applying database migration
fermentrack    | Traceback (most recent call last):
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 273, in get_value
fermentrack    |     value = self.ENVIRON[var]
fermentrack    |   File "/usr/lib/python3.7/os.py", line 678, in __getitem__
fermentrack    |     raise KeyError(key) from None
fermentrack    | KeyError: 'DJANGO_SECRET_KEY'
fermentrack    |
fermentrack    | During handling of the above exception, another exception occurred:
fermentrack    |
fermentrack    | Traceback (most recent call last):
fermentrack    |   File "manage.py", line 25, in <module>
fermentrack    |     execute_from_command_line(sys.argv)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
fermentrack    |     utility.execute()
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
fermentrack    |     self.fetch_command(subcommand).run_from_argv(self.argv)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
fermentrack    |     self.execute(*args, **cmd_options)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/base.py", line 366, in execute
fermentrack    |     self.check()
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/base.py", line 395, in check
fermentrack    |     include_deployment_checks=include_deployment_checks,
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
fermentrack    |     issues = run_checks(tags=[Tags.database])
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
fermentrack    |     new_errors = check(app_configs=app_configs)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/checks/database.py", line 9, in check_database_backends
fermentrack    |     for conn in connections.all():
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/db/utils.py", line 222, in all
fermentrack    |     return [self[alias] for alias in self]
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/db/utils.py", line 219, in __iter__
fermentrack    |     return iter(self.databases)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
fermentrack    |     res = instance.__dict__[self.name] = self.func(instance)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/db/utils.py", line 153, in databases
fermentrack    |     self._databases = settings.DATABASES
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
fermentrack    |     self._setup(name)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
fermentrack    |     self._wrapped = Settings(settings_module)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
fermentrack    |     mod = importlib.import_module(self.SETTINGS_MODULE)
fermentrack    |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
fermentrack    |     return _bootstrap._gcd_import(name[level:], package, level)
fermentrack    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
fermentrack    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
fermentrack    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
fermentrack    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
fermentrack    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
fermentrack    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
fermentrack    |   File "/home/fermentrack/fermentrack/fermentrack_django/settings.py", line 26, in <module>
fermentrack    |     SECRET_KEY = env("DJANGO_SECRET_KEY")
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 123, in __call__
fermentrack    |     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
fermentrack    |   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 277, in get_value
fermentrack    |     raise ImproperlyConfigured(error_msg)
fermentrack    | django.core.exceptions.ImproperlyConfigured: Set the DJANGO_SECRET_KEY environment variable
fermentrack    | Version/Source of fermentrack installed in image:
fermentrack    | ****************************************************************
fermentrack    | origin https://github.com/thorrak/fermentrack.git (fetch)
fermentrack    | origin https://github.com/thorrak/fermentrack.git (push)
fermentrack    |
fermentrack    | commit 02391da4b303e1b1b53745a4cc56fa4e08934632
fermentrack    | Author: Thorrak <thorrak@excelinspace.com>
fermentrack    |
fermentrack    |     Finalize changelog for release
fermentrack    | ****************************************************************
fermentrack    | Starting circus deamon

**Comment by jbonnet69** [comment]
Same issue for me.
